### ISSUE TITLE
ChainedDeconstruction: Broken since today's patch

### ISSUE THREAD

**Issue by shagura1980** [EtiamNullam/Etiam-ONI-Modpack#9]
As title says,CD is not working anymore since today's ONI patch. All other mods are fine for me,but if i try to activate CD it just begin a loop where game ask me to restart and then restart again until it become non active. Also in the mod selection in the ONI MENU', CD is marked RED. I love this mod anc cant really play without it,can you fix this pls? Thanks!

**Comment by EtiamNullam** [comment]
Post `output_log.txt` from failed launch with `ChainedDeconstruction` activated so I can investigate.

**Comment by shagura1980** [comment]
[output_log.txt](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/4593094/output_log.txt)
This is the log you want i guess. Thx for the reply

**Comment by EtiamNullam** [comment]
Thanks, but `ChainedDeconstruction` is not initialized here. Try this: enable mod, restart game then save the `output_log.txt`.

You might also try: unsubscribe, launch game then resubscribe to `ChainedDeconstruction`. Yet its unlikely it will help.

EDIT: If you can its best to test this while deactivating every other mod to narrow it down.

**Comment by shagura1980** [comment]
Ok,i got it. Thanks for your help. the problem was that the game just loops the installing and uninstalling cd. I've done what you said, unsubscribed,than launch the game without CD,then quit the game,go to workshop and subscribe again. that worked. In the meantime,i unsubscribed another mod (deconstructible POI) that was marked red and not working too. Maybe it doesnt matter,but with those two things,i fixed. Thanks for your patience. And,BTW,most useful mod for this game.

**Comment by EtiamNullam** [comment]
Thank you for solving the issue!

Looks like its something about steam workshop or the game itself. Don't hesitate and re-open this issue if you want to share any additional relevant information.

**Comment by EtiamNullam** [comment]
Apparently some people still have problem running `ChainedDeconstruction` in 408920.

If it doesn't work for you please provide `output_log.txt` from failed launch. Also try running the game with only `ChainedDeconstruction` mod enabled.

**Comment by fooodball** [comment]
Hi, I have unable to use the mod so this is my output_log from failed launch. thx
[output_log.txt](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/4602843/output_log.txt)

**Comment by EtiamNullam** [comment]
@fooodball Thanks! Looks like game tries to remove mod directory but has no access.

Have you tried unsubscribe and resubscribe method that worked for @shagura1980 above?

You can try remove directory located at `%userprofile%\Documents\Klei\OxygenNotIncluded\mods\Steam\1737893485` manually.

I don't know why there is access restricted there, maybe restarting PC would help.

Let me know if anything helps.

**Comment by OriginalFoamy** [comment]
Uninstalled/reinstalled approximately 6 times. Still not working. Reading the above comments, I also had issues with Deconstructible POI mods and have removed it completely.  Also attempted to delete and reinstall CD after the update. 

Same issue as described above, constant loops of installing and closing, restarting, and failing to load.
"An Unsufficient Space Error occurred when trying to Write to Disk"

On the assumption that maybe disk space was an issue, I also checked available space on that drive. Ive got at least 100Gb free, so I fail to understand...

[output_log.txt](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/4606506/output_log.txt)

**Comment by EtiamNullam** [comment]
@OriginalFoamy: Looks like you have a completely different issue - your log shows an [error that appeared during last test branch](https://github.com/EtiamNullam/Etiam-ONI-Modpack/issues/5).

`An Unsufficient Space Error occurred when trying to Write to Disk` - this message is often wrong and its displayed when game can't access some mod files. I got when I wanted to uninstall a mod, but I had a text editor open in it.

Also looks like you are using some mod manager. I bet that's why game has some issues with access - game tries to uninstall mod and get new version but mod manager won't let it. Try removing this mod manager.

Also check version of `ChainedDeconstruction.dll` located at `%userprofile%\Documents\Klei\OxygenNotIncluded\mods\Steam\1737893485` it should be currently at `2.2.1` (mouse-over or check in Properties->Details):

![image](https://user-images.githubusercontent.com/10875340/81509922-6023b700-930e-11ea-968e-e48717b99d61.png).

Sometimes Steam Workshop makes you download wrong mod version, but I doubt that's the issue here.

**Comment by EtiamNullam** [comment]
@fooodball, @OriginalFoamy: Anyway I'm pretty sure you have wrong version of the mod and something prevents game from updating it.

If it still doesn't work for you - check mod version.
![image](https://user-images.githubusercontent.com/10875340/81509922-6023b700-930e-11ea-968e-e48717b99d61.png)
If its `2.2` or less mod is outdated and you have to force it to be downloaded again somehow, you can try this:

1. Exit game.
2. Unsubscribe from `ChainedDeconstruction`.
3. Make sure directory `1737893485` does not exist at `%userprofile%\Documents\Klei\OxygenNotIncluded\mods\Steam` (If it exists - delete it).
4. Launch game to check if it launches correctly.
5. If you can disable all other mods to make sure they don't conflict.
6. Exit game.
7. Subscribe to `ChainedDecostruction`.
8. Launch game.
9. Check `ChaindDeconstruction` version again. If the mod version is `2.2.1` now or above it has to work. 

In any case please tell me what u tried and whether it helped or not.

**Comment by OriginalFoamy** [comment]
Looks like that probably would have worked. @Ony apparently updated the mod manager, and then I deleted, unsubscribed, resubscribed, and started/restarted ONI a few times, and it is working correctly now. Thanks for all your help.

**Comment by fooodball** [comment]
thanks, I did have the older version of it but now it's solved!!

**Comment by EtiamNullam** [comment]
Ok, thanks for letting me know. I'm glad it works.
